[ifttt]
# https://ifttt.com/services/maker_webhooks/settings
key = '...'

[connections.main]
# https://trello.com/app-key
key = '...'
token = '...'
oauth_secret = '...'

[[rules]]
# name of trello connection
connection = 'main'
# name of IFTTT webhook event
event = '...'
# trello board name
board = '...'
# trello list name
list = '...'
# fields from card to values in IFTTT webhook
# available fields: description, name, due_date
fields = ['description', 'name', 'due_date']
# available converters:
# html:             Markdown -> HTML
# telegram_html:    Markdown -> Telegram compatible HTML
# dash:             -- -> â€”
# links:            word link -> [word](link)
converters = ['telegram_html', 'dash', 'links']
# delete card after rule apply
delete = true
